/*
 * Pyx4j framework
 * Copyright (C) 2008-2013 pyx4j.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * Created on Mar 11, 2014
 * @author vlads
 * @version $Id$
 */
package com.pyx4j.entity.rdb.poc.dls;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

import javax.sql.DataSource;

import org.apache.commons.dbcp2.ConnectionFactory;
import org.apache.commons.dbcp2.DriverManagerConnectionFactory;
import org.apache.commons.dbcp2.PoolableConnection;
import org.apache.commons.dbcp2.PoolableConnectionFactory;
import org.apache.commons.dbcp2.PoolingDataSource;
import org.apache.commons.pool2.impl.GenericObjectPool;

import com.mchange.v2.c3p0.ComboPooledDataSource;

public class DaylightSavingJDBC {

    static String dateTimeInSaylightSavingDay;

    /** Hours that will produce this problem 3AM, 4AM, 5AM and 6AM */
    static int testHour = 6;

    static {
        // daylight saving time in EDT  2014-03-09  from 2:00 jumps to -> 3:00
        //http://www.timetemperature.com/canada/daylight_saving_time_canada.shtml
        dateTimeInSaylightSavingDay = "2014-03-09 06:21:28";

        // Other dates with the same problem
        //dateTimeInSaylightSavingDay = "2009-03-08 06:21:28";
        //dateTimeInSaylightSavingDay = "2010-03-14 06:21:28";
        //dateTimeInSaylightSavingDay = "2015-03-08 06:21:28";
    }

    enum DBType {
        HSQL, MySQL, PostgreSql, Oracle
    }

    static boolean init = true;

    static boolean firstRun = true;

    public static void main(String[] args) throws Exception {
        Connection con;

        DBType testDB;

        //testDB = DBType.HSQL;
        //testDB = DBType.MySQL;
        testDB = DBType.PostgreSql;

        String driverClass;
        String url;
        String user;
        String password;

        switch (testDB) {
        case HSQL: {
            driverClass = "org.hsqldb.jdbcDriver";
            Class.forName(driverClass);
            url = "jdbc:hsqldb:mem:tst_entity";
            user = "sa";
            password = "";
            con = DriverManager.getConnection(url, user, password);
            // Create test Table
            if (init) {
                init = false;
                con.createStatement()
                        .executeUpdate(
                                "CREATE TABLE test(id bigint generated by default as identity (start with 1),  name varchar(500), dval timestamp,  CONSTRAINT TEST_PK PRIMARY KEY (id))");
            }
            break;
        }
        case MySQL: {
            driverClass = "com.mysql.jdbc.Driver";
            Class.forName(driverClass).newInstance();

            url = "jdbc:mysql://localhost/tst_entity";
            user = "tst_entity";
            password = "tst_entity";
            con = DriverManager.getConnection(url, user, password);

            if (init) {
                init = false;
                con.createStatement().executeUpdate(
                        "CREATE TABLE test(id bigint(20) NOT NULL AUTO_INCREMENT, name varchar(500), dval datetime,  CONSTRAINT TEST_PK PRIMARY KEY (id))");
            } else {
                con.createStatement().executeUpdate("DELETE FROM test");
            }
            break;
        }
        case PostgreSql: {
            driverClass = "org.postgresql.Driver";
            Class.forName(driverClass).newInstance();

            url = "jdbc:postgresql://localhost/tst_entity";
            user = "tst_entity";
            password = "tst_entity";
            con = DriverManager.getConnection(url, user, password);

            if (init) {
                init = false;
                try {
                    con.createStatement().executeUpdate(
                            "CREATE TABLE test(id SERIAL NOT NULL, name varchar(500), dval timestamp, CONSTRAINT TEST_PK PRIMARY KEY (id))");
                } catch (SQLException e) {
                    if (!e.getMessage().contains("already exists")) {
                        throw e;
                    }
                }
            } else {
                con.createStatement().executeUpdate("DELETE FROM test");
            }
            break;
        }
        default:
            throw new IllegalArgumentException();
        }

        con.setAutoCommit(false);
        con.createStatement();

        //Setup test data
        String uniqueName = "TestDate#" + System.nanoTime();

        // Save event in day when daylight saving change happened 
        {
            PreparedStatement stmt = con.prepareStatement("INSERT INTO test (name, dval)  VALUES (?, ?)");

            stmt.setString(1, uniqueName);
            Date date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.ENGLISH).parse(dateTimeInSaylightSavingDay);
            stmt.setTimestamp(2, new java.sql.Timestamp(date.getTime()));

            stmt.executeUpdate();

        }

        con.commit();

        ComboPooledDataSource dataSourceC3PO = new ComboPooledDataSource(true);
        {
            dataSourceC3PO.setDriverClass(driverClass);
            dataSourceC3PO.setJdbcUrl(url);
            dataSourceC3PO.setUser(user);
            dataSourceC3PO.setPassword(password);

            dataSourceC3PO.setMaxPoolSize(5);

            dataSourceC3PO.setMaxStatements(200); //   <-------------------- this makes the difference  (0 is OK)
        }

        DataSource dataSourceDBCP;
        GenericObjectPool<PoolableConnection> connectionPool;
        {
            ConnectionFactory driverConnectionFactory = new DriverManagerConnectionFactory(url, user, password);

            PoolableConnectionFactory poolableConnectionFactory = new PoolableConnectionFactory(driverConnectionFactory, null);

            poolableConnectionFactory.setPoolStatements(true); //   <-------------------- this makes the difference  (false is OK)
            poolableConnectionFactory.setMaxOpenPrepatedStatements(30);

            connectionPool = new GenericObjectPool<>(poolableConnectionFactory);
            connectionPool.setMaxTotal(3);

            poolableConnectionFactory.setPool(connectionPool);
            dataSourceDBCP = new PoolingDataSource<PoolableConnection>(connectionPool);
        }

        try {
            for (int i = 0; i <= 20; i++) {

                Connection con2;

                //con2 = con; // <-------------  Not pooled connection works fine!
                //con2 = DriverManager.getConnection(url, user, password); // <-------------  Driver Managed connection works fine!
                //con2 = dataSourceC3PO.getConnection(); // <-- this will create error
                con2 = dataSourceDBCP.getConnection(); // <-- this will create error

                String sql = "SELECT dval FROM test  WHERE name = ?";
                PreparedStatement stmt = con2.prepareStatement(sql);
                stmt.setString(1, uniqueName);

                ResultSet rs = stmt.executeQuery();
                try {
                    if (rs.next()) {

                        java.sql.Timestamp value;

                        value = rs.getTimestamp("dval");
                        //value = rs.getTimestamp("dval", Calendar.getInstance()); // <-- this changes nothing

                        Calendar c = Calendar.getInstance();
                        c.setTime(value);

                        //System.out.println(value.getTimezoneOffset()); // this prints the same value

                        if (testHour != c.get(Calendar.HOUR_OF_DAY)) {
                            throw new Error("try# " + i + "; hour of " + value + " expected " + testHour + " but was " + c.get(Calendar.HOUR_OF_DAY));
                        }
                    } else {
                        throw new Error();
                    }
                } finally {
                    rs.close();
                }

                if (con2 != con) { // if pooled connection
                    con2.close();
                }
            }
        } finally {
            dataSourceC3PO.close();
            connectionPool.close();
            con.close();
        }

        if (firstRun) {
            System.out.println("Ok :) no problem with date: " + dateTimeInSaylightSavingDay);
            firstRun = false;
        }

    }
}
