//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 12:18:12 PM EDT 
//


package com.propertyvista.portal.server.portal.services.resident.weather.openweathermap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.propertyvista.portal.server.portal.services.resident.weather.openweathermap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.propertyvista.portal.server.portal.services.resident.weather.openweathermap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Weatherdata }
     * 
     */
    public Weatherdata createWeatherdata() {
        return new Weatherdata();
    }

    /**
     * Create an instance of {@link Weatherdata.Forecast }
     * 
     */
    public Weatherdata.Forecast createWeatherdataForecast() {
        return new Weatherdata.Forecast();
    }

    /**
     * Create an instance of {@link Weatherdata.Forecast.Time }
     * 
     */
    public Weatherdata.Forecast.Time createWeatherdataForecastTime() {
        return new Weatherdata.Forecast.Time();
    }

    /**
     * Create an instance of {@link Weatherdata.Location }
     * 
     */
    public Weatherdata.Location createWeatherdataLocation() {
        return new Weatherdata.Location();
    }

    /**
     * Create an instance of {@link Weatherdata.Meta }
     * 
     */
    public Weatherdata.Meta createWeatherdataMeta() {
        return new Weatherdata.Meta();
    }

    /**
     * Create an instance of {@link Weatherdata.Sun }
     * 
     */
    public Weatherdata.Sun createWeatherdataSun() {
        return new Weatherdata.Sun();
    }

    /**
     * Create an instance of {@link Weatherdata.Forecast.Time.Symbol }
     * 
     */
    public Weatherdata.Forecast.Time.Symbol createWeatherdataForecastTimeSymbol() {
        return new Weatherdata.Forecast.Time.Symbol();
    }

    /**
     * Create an instance of {@link Weatherdata.Forecast.Time.Precipitation }
     * 
     */
    public Weatherdata.Forecast.Time.Precipitation createWeatherdataForecastTimePrecipitation() {
        return new Weatherdata.Forecast.Time.Precipitation();
    }

    /**
     * Create an instance of {@link Weatherdata.Forecast.Time.WindDirection }
     * 
     */
    public Weatherdata.Forecast.Time.WindDirection createWeatherdataForecastTimeWindDirection() {
        return new Weatherdata.Forecast.Time.WindDirection();
    }

    /**
     * Create an instance of {@link Weatherdata.Forecast.Time.WindSpeed }
     * 
     */
    public Weatherdata.Forecast.Time.WindSpeed createWeatherdataForecastTimeWindSpeed() {
        return new Weatherdata.Forecast.Time.WindSpeed();
    }

    /**
     * Create an instance of {@link Weatherdata.Forecast.Time.Temperature }
     * 
     */
    public Weatherdata.Forecast.Time.Temperature createWeatherdataForecastTimeTemperature() {
        return new Weatherdata.Forecast.Time.Temperature();
    }

    /**
     * Create an instance of {@link Weatherdata.Forecast.Time.Pressure }
     * 
     */
    public Weatherdata.Forecast.Time.Pressure createWeatherdataForecastTimePressure() {
        return new Weatherdata.Forecast.Time.Pressure();
    }

    /**
     * Create an instance of {@link Weatherdata.Forecast.Time.Humidity }
     * 
     */
    public Weatherdata.Forecast.Time.Humidity createWeatherdataForecastTimeHumidity() {
        return new Weatherdata.Forecast.Time.Humidity();
    }

    /**
     * Create an instance of {@link Weatherdata.Forecast.Time.Clouds }
     * 
     */
    public Weatherdata.Forecast.Time.Clouds createWeatherdataForecastTimeClouds() {
        return new Weatherdata.Forecast.Time.Clouds();
    }

    /**
     * Create an instance of {@link Weatherdata.Location.GeoLocation }
     * 
     */
    public Weatherdata.Location.GeoLocation createWeatherdataLocationGeoLocation() {
        return new Weatherdata.Location.GeoLocation();
    }

}
