/*
 * (C) Copyright Property Vista Software Inc. 2011- All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Property Vista Software Inc. ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the license agreement
 * you entered into with Property Vista Software Inc.
 *
 * This notice and attribution to Property Vista Software Inc. may not be removed.
 *
 * Created on 2011-06-13
 * @author vlads
 * @version $Id$
 */
package com.propertyvista.domain.pmc;

import java.math.BigDecimal;

import com.pyx4j.entity.annotations.Caption;
import com.pyx4j.entity.annotations.Detached;
import com.pyx4j.entity.annotations.Editor;
import com.pyx4j.entity.annotations.Editor.EditorType;
import com.pyx4j.entity.annotations.EmbeddedEntity;
import com.pyx4j.entity.annotations.Indexed;
import com.pyx4j.entity.annotations.JoinColumn;
import com.pyx4j.entity.annotations.Length;
import com.pyx4j.entity.annotations.MemberColumn;
import com.pyx4j.entity.annotations.Owned;
import com.pyx4j.entity.annotations.Owner;
import com.pyx4j.entity.annotations.ReadOnly;
import com.pyx4j.entity.annotations.Table;
import com.pyx4j.entity.shared.IEntity;
import com.pyx4j.entity.shared.IPrimitive;
import com.pyx4j.i18n.annotations.I18n;

import com.propertyvista.domain.VistaNamespace;
import com.propertyvista.domain.pmc.info.BusinessInformation;
import com.propertyvista.domain.pmc.info.PersonalInformation;
import com.propertyvista.domain.security.PasswordIdentity;

@Table(prefix = "admin", namespace = VistaNamespace.operationsNamespace)
@Caption(name = "PMC Equifax Info")
@I18n(strategy = I18n.I18nStrategy.IgnoreAll)
public interface PmcEquifaxInfo extends IEntity {

    IPrimitive<PmcEquifaxStatus> status();

    @ReadOnly
    @Owner
    @MemberColumn(notNull = true)
    @JoinColumn
    @Indexed(uniqueConstraint = true)
    @Detached
    Pmc pmc();

    IPrimitive<CreditCheckReportType> reportType();

    //@Length(10)
    PasswordIdentity memberNumber();

    //@Length(2)
    PasswordIdentity securityCode();

    @Length(4)
    IPrimitive<String> customerCode();

    // This should probably be autogenerated value a PMC id()
    @Length(12)
    IPrimitive<String> customerReferenceNumber();

    @Detached
    PmcPaymentMethod paymentMethod();

    @Editor(type = EditorType.money)
    IPrimitive<BigDecimal> equifaxSignUpFee();

    @Editor(type = EditorType.money)
    IPrimitive<BigDecimal> equifaxPerApplicantCreditCheckFee();

    @EmbeddedEntity
    EquifaxLimit limit();

    @Owned
    @Detached
    BusinessInformation businessInformation();

    @Owned
    @Detached
    PersonalInformation personalInformation();

}
