/*
 * (C) Copyright Property Vista Software Inc. 2011- All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Property Vista Software Inc. ("Confidential Information"). 
 * You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the license agreement 
 * you entered into with Property Vista Software Inc.
 *
 * This notice and attribution to Property Vista Software Inc. may not be removed.
 *
 * Created on Jan 26, 2011
 * @author michaellif
 * @version $Id$
 */
package com.propertyvista.domain.property.asset;

import java.sql.Date;

import com.pyx4j.entity.annotations.Caption;
import com.pyx4j.entity.annotations.Detached;
import com.pyx4j.entity.annotations.Editor;
import com.pyx4j.entity.annotations.Editor.EditorType;
import com.pyx4j.entity.annotations.Format;
import com.pyx4j.entity.annotations.Length;
import com.pyx4j.entity.annotations.MemberColumn;
import com.pyx4j.entity.annotations.Owned;
import com.pyx4j.entity.annotations.ToString;
import com.pyx4j.entity.annotations.ToStringFormat;
import com.pyx4j.entity.shared.IEntity;
import com.pyx4j.entity.shared.IList;
import com.pyx4j.entity.shared.IPrimitive;
import com.pyx4j.i18n.shared.I18nEnum;
import com.pyx4j.i18n.shared.Translatable;
import com.pyx4j.i18n.shared.Translation;

import com.propertyvista.common.domain.financial.Currency;
import com.propertyvista.domain.Address;
import com.propertyvista.domain.Email;
import com.propertyvista.domain.Medium;
import com.propertyvista.domain.OrganizationContacts;
import com.propertyvista.domain.Phone;

@ToStringFormat("{0} {1}")
//TODO rename to Property
public interface Building extends IEntity {

    @Translatable
    public enum Type {

        agricultural,

        commercial,

        mixed_residential,

        residential,

        industrial,

        military,

        parking_storage,

        other;

        @Override
        public String toString() {
            return I18nEnum.tr(this);
        }
    }

    @Translatable
    public enum Shape {

        regular,

        @Translation("L-shape")
        lShape,

        @Translation("T-shape")
        tShape,

        @Translation("U-shape")
        uShape,

        irregular;

        @Override
        public String toString() {
            return I18nEnum.tr(this);
        }
    }

    @Translatable
    public enum StructureType {

        @Translation("Low-Rise")
        lowRise,

        @Translation("High-Rise")
        highRise,

        @Translation("Mid-Rise")
        midRise,

        @Translation("Walk-up")
        walkUp,

        townhouse,

        condo,

        other;

        @Override
        public String toString() {
            return I18nEnum.tr(this);
        }
    }

    @Translatable
    public enum ConstructionType {

        brick,

        wood,

        block,

        panel,

        other;

        @Override
        public String toString() {
            return I18nEnum.tr(this);
        }
    }

    @Translatable
    public enum FoundationType {

        pile,

        continuousFooting,

        spreadFooting,

        foundationWalls,

        other;

        @Override
        public String toString() {
            return I18nEnum.tr(this);
        }
    }

    @Translatable
    public enum FloorType {

        hardwood,

        tile,

        laminate,

        carpet,

        mixed,

        other;

        @Override
        public String toString() {
            return I18nEnum.tr(this);
        }
    }

    @Translatable
    public enum WaterSupply {

        municipal,

        privateWell,

        privateCommunityWell,

        other;

        @Override
        public String toString() {
            return I18nEnum.tr(this);
        }
    }

    // -----------Buiding Infromation---------------------------------------------------------------------------

    /**
     * Legal name of the property (max 120 char)
     */
    IPrimitive<String> name();

    @ToString(index = 1)
    Address address();

    // TODO: To be auto-generated by system unless user enters his own value. (Can be modified (by accounting)).
    //          It seems that two buttons are required: Validate (on Uniqueness) and Generate (new one).
    @Caption(name = "Building Code")
    IPrimitive<String> propertyCode();

    @ToString(index = 0)
    @MemberColumn(name = "buildingType")
    IPrimitive<Type> type();

    IPrimitive<Type> shape();

    IPrimitive<String> totalStories();

    IPrimitive<String> residentialStories();

    IPrimitive<StructureType> structureType();

    @Format("yyyy")
    @Editor(type = EditorType.yearpicker)
    IPrimitive<Date> structureBuildYear();

    // ------------Building Details--------------------------------------------------------------------------

    IList<Elevator> elevators();

    IList<Boiler> boilers();

    Roof roofData();

    IList<Parking> parkings();

    IList<Locker> lockers();

    IList<BuildingAmenity> amenities();

    IPrimitive<ConstructionType> constructionType();

    IPrimitive<FoundationType> foundationType();

    IPrimitive<Boolean> centralAir();

    IPrimitive<Boolean> centralHeat();

    IPrimitive<FloorType> floorType();

    IPrimitive<String> landArea();

    IPrimitive<WaterSupply> waterSupply();

    // ------------------Financial--------------------------------------------------------------------

    IPrimitive<Date> dateAquired();

    @Format("#0.00")
    IPrimitive<Double> purchasePrice();

    @Format("#0.00")
    IPrimitive<Double> marketPrice();

    IPrimitive<Date> lastAppraisalDate();

    @Format("#0.00")
    IPrimitive<Double> lastAppraisalValue();

    /*
     * Type of currency used for this particular building
     * in all money-related fields.
     */
    Currency currency();

    // ----------------Contact information----------------------------------------------------------------------

    @Length(100)
    IPrimitive<String> website();

    @Owned
    Email email(); // email business is not clear at the moment, we need a bit more detail on this

    @Owned
    IList<Phone> phoneList();

// TODO discuss with Artur which contacts fill here!..    
    IList<OrganizationContacts> contactsList();

    // -----------------------Marketing---------------------------------------------------------------
    /**
     * Property name used for marketing purposes (max 120 char)
     */
    IPrimitive<String> marketingName();

    /**
     * Property description used for marketing purposes
     */
    IPrimitive<String> marketingDescription();

    // TODO - add list of property owners here...

    @Detached
    IList<Medium> media();

// --------------------------------------------------------------------------------------

    // there is a drop-down box with create new complex  
    Complex complex();
}
