/*
 * Pyx4j framework
 * Copyright (C) 2008-2011 pyx4j.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * Created on Feb 9, 2012
 * @author vlads
 * @version $Id$
 */
package com.pyx4j.entity.rdb.mapping;

import com.pyx4j.entity.annotations.Owned;
import com.pyx4j.entity.annotations.Owner;
import com.pyx4j.entity.annotations.Table;
import com.pyx4j.entity.rdb.dialect.Dialect;
import com.pyx4j.entity.rdb.dialect.NamingConvention;
import com.pyx4j.entity.shared.EntityFactory;
import com.pyx4j.entity.shared.IEntity;
import com.pyx4j.entity.shared.meta.EntityMeta;
import com.pyx4j.entity.shared.meta.MemberMeta;

public class JoinOwnerInformation extends JoinInformation {

    public JoinOwnerInformation(Dialect dialect, NamingConvention namingConvention, EntityMeta rootEntityMeta, EntityMeta entityMeta, MemberMeta memberMeta,
            Owner owner) {

        @SuppressWarnings("unchecked")
        Class<? extends IEntity> ownerEntityClass = (Class<IEntity>) memberMeta.getValueClass();
        EntityMeta ownerEntityMeta = EntityFactory.getEntityMeta(ownerEntityClass);
        MemberMeta ownedMemberMeta = findOwnedMember(entityMeta, memberMeta, rootEntityMeta, owner, ownerEntityMeta);

        switch (ownedMemberMeta.getObjectClassType()) {
        case Entity:
            joinTableClass = ownerEntityClass;
            joinTableSameAsTarget = true;
            sqlName = TableModel.getTableName(dialect, ownerEntityMeta);
            sqlValueName = IEntity.PRIMARY_KEY;
            sqlOwnerName = namingConvention.sqlFieldName(EntityOperationsMeta.memberPersistenceName(ownedMemberMeta));
            ownerValueAdapter = EntityOperationsMeta.createEntityValueAdapter(dialect, ownedMemberMeta);
            break;
        case EntityList:
        case EntitySet:
            // One-to-Many, JT auto generated
            joinTableClass = ownerEntityClass;
            joinTableSameAsTarget = false;
            sqlName = namingConvention.sqlChildTableName(ownerEntityMeta.getPersistenceName(), EntityOperationsMeta.memberPersistenceName(ownedMemberMeta));
            sqlValueName = namingConvention.sqlAutoGeneratedJoinOwnerColumnName();
            sqlOwnerName = namingConvention.sqlAutoGeneratedJoinValueColumnName();
            ownerValueAdapter = EntityOperationsMeta.createEntityValueAdapter(dialect, ownedMemberMeta);
            break;
        default:
            throw new AssertionError();
        }
    }

    private MemberMeta findOwnedMember(EntityMeta entityMeta, MemberMeta memberMeta, EntityMeta rootEntityMeta, Owner owner, EntityMeta ownerEntityMeta) {
        MemberMeta ownerMemberMeta = null;

        Class<? extends IEntity> rootEntityClass = rootEntityMeta.getEntityClass();
        Table tableAnnotation = rootEntityMeta.getAnnotation(Table.class);
        if ((tableAnnotation != null) && (tableAnnotation.expands() != IEntity.class)) {
            rootEntityClass = tableAnnotation.expands();
        }

        for (String jmemberName : ownerEntityMeta.getMemberNames()) {
            MemberMeta jmemberMeta = ownerEntityMeta.getMemberMeta(jmemberName);
            if (!jmemberMeta.isTransient() && (jmemberMeta.getAnnotation(Owned.class) != null)) {
                if ((jmemberMeta.getValueClass().equals(rootEntityMeta.getEntityClass())) || (jmemberMeta.getValueClass().equals(rootEntityClass))) {
                    if (ownerMemberMeta != null) {
                        throw new AssertionError("Duplicate @Owned member in join table '" + ownerEntityMeta.getEntityClass().getName() + "' for "
                                + memberMeta.getFieldName() + " of type " + entityMeta.getEntityClass().getName());
                    }
                    ownerMemberMeta = jmemberMeta;
                }
            }
        }
        if (ownerMemberMeta == null) {
            throw new AssertionError("Unmapped @Owned member in join table '" + ownerEntityMeta.getEntityClass().getName() + "' for "
                    + memberMeta.getFieldName() + " of type " + entityMeta.getEntityClass().getName());
        } else {
            return ownerMemberMeta;
        }
    }

}
