/*
 * Pyx4j framework
 * Copyright (C) 2008-2011 pyx4j.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * Created on Jan 6, 2012
 * @author vlads
 * @version $Id$
 */
package com.pyx4j.entity.rdb.mapping;

import com.pyx4j.entity.core.IEntity;
import com.pyx4j.entity.core.meta.MemberMeta;

public class MemberCollectionOperationsMeta extends MemberExternalOperationsMeta {

    private final boolean autogenerated;

    private final MemberCollectionOrderMeta collectionOrderMeta;

    public MemberCollectionOperationsMeta(EntityMemberAccess memberAccess, ValueAdapter valueAdapter, String sqlName, MemberMeta memberMeta, String memberPath,
            Class<? extends IEntity> joinTableClass, boolean joinTableSameAsTarget, String sqlOwnerName, ValueAdapter ownerValueAdapter, String sqlValueName,
            MemberCollectionOrderMeta collectionOrderMeta, String sqlChildJoinContition, boolean autogenerated) {
        super(memberAccess, valueAdapter, sqlName, memberMeta, memberPath, joinTableClass, joinTableSameAsTarget, sqlOwnerName, ownerValueAdapter,
                sqlValueName, sqlChildJoinContition);
        this.collectionOrderMeta = collectionOrderMeta;
        this.autogenerated = autogenerated;
    }

    public String sqlOrderColumnName() {
        return collectionOrderMeta.sqlOrderColumnName();
    }

    public boolean isOrderMaterialized() {
        return (collectionOrderMeta != null) && collectionOrderMeta.isOrderMaterialized();
    }

    public String orderMemberName() {
        return collectionOrderMeta.orderMemberName();
    }

    public boolean isAutogenerated() {
        return autogenerated;
    }

    @Override
    public String toString() {
        return super.toString() + " Collection";
    }
}
