package com.propertyvista.yardi.jaxws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GreetingImplService", targetNamespace = "http://jaxws.yardi.propertyvista.com/", wsdlLocation = "http://localhost:8888/WS/Greeting?wsdl")
@HandlerChain(file = "client-handler-chain.xml")
public class GreetingImplService extends Service {

    private final static URL GREETINGIMPLSERVICE_WSDL_LOCATION;

    private final static WebServiceException GREETINGIMPLSERVICE_EXCEPTION;

    private final static QName GREETINGIMPLSERVICE_QNAME = new QName("http://jaxws.yardi.propertyvista.com/", "GreetingImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/WS/Greeting?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GREETINGIMPLSERVICE_WSDL_LOCATION = url;
        GREETINGIMPLSERVICE_EXCEPTION = e;
    }

    public GreetingImplService() {
        super(__getWsdlLocation(), GREETINGIMPLSERVICE_QNAME);
    }

    public GreetingImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GREETINGIMPLSERVICE_QNAME, features);
    }

    public GreetingImplService(URL wsdlLocation) {
        super(wsdlLocation, GREETINGIMPLSERVICE_QNAME);
    }

    public GreetingImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GREETINGIMPLSERVICE_QNAME, features);
    }

    public GreetingImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GreetingImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *         returns Greeting
     */
    @WebEndpoint(name = "GreetingImplPort")
    public Greeting getGreetingImplPort() {
        return super.getPort(new QName("http://jaxws.yardi.propertyvista.com/", "GreetingImplPort"), Greeting.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will
     *            have their default values.
     * @return
     *         returns Greeting
     */
    @WebEndpoint(name = "GreetingImplPort")
    public Greeting getGreetingImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.yardi.propertyvista.com/", "GreetingImplPort"), Greeting.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GREETINGIMPLSERVICE_EXCEPTION != null) {
            throw GREETINGIMPLSERVICE_EXCEPTION;
        }
        return GREETINGIMPLSERVICE_WSDL_LOCATION;
    }

}
