/**
***     ======================================================================================================================
***
***             @version $Revision$ ($Author$) $Date$
***
***             Per-building statistics tables
***
***     ======================================================================================================================
**/

CREATE TABLE _dba_.building_stats 
(
        pmc                             VARCHAR(150),
        property_code                   VARCHAR(20),
        stats_week                      DATE,
        total_units                     INT                     DEFAULT 0,
        active_leases                   INT                     DEFAULT 0,
        reg_units                       INT                     DEFAULT 0,
        units_epay                      INT                     DEFAULT 0,
        reg_units_epay                  INT                     DEFAULT 0,
        total_tenants                   INT                     DEFAULT 0,
        reg_tenants                     INT                     DEFAULT 0,
        tenants_epay                    INT                     DEFAULT 0,
        reg_tenants_epay                INT                     DEFAULT 0,
        count_trans_all                 INT                     DEFAULT 0,
        amount_trans_all                NUMERIC(18,2)           DEFAULT 0.00,
        count_trans_recur               INT                     DEFAULT 0,
        amount_trans_recur              NUMERIC(18,2)           DEFAULT 0.00,
        count_trans_onetime             INT                     DEFAULT 0,
        amount_trans_onetime            NUMERIC(18,2)           DEFAULT 0.00,
        count_eft_recur                 INT                     DEFAULT 0,
        amount_eft_recur                NUMERIC(18,2)           DEFAULT 0.00,
        count_eft_onetime               INT                     DEFAULT 0,
        amount_eft_onetime              NUMERIC(18,2)           DEFAULT 0.00,
        count_direct_debit              INT                     DEFAULT 0,
        amount_direct_debit             NUMERIC(18,2)           DEFAULT 0.00,
        count_interac                   INT                     DEFAULT 0,
        amount_interac                  NUMERIC(18,2)           DEFAULT 0.00,
        count_visa_recur                INT                     DEFAULT 0,
        amount_visa_recur               NUMERIC(18,2)           DEFAULT 0.00,
        count_visa_onetime              INT                     DEFAULT 0,
        amount_visa_onetime             NUMERIC(18,2)           DEFAULT 0.00,
        count_mc_recur                  INT                     DEFAULT 0,
        amount_mc_recur                 NUMERIC(18,2)           DEFAULT 0.00,
        count_mc_onetime                INT                     DEFAULT 0,
        amount_mc_onetime               NUMERIC(18,2)           DEFAULT 0.00,
        count_visadebit_recur           INT                     DEFAULT 0,
        amount_visadebit_recur          NUMERIC(18,2)           DEFAULT 0.00,
        count_visadebit_onetime         INT                     DEFAULT 0,
        amount_visadebit_onetime        NUMERIC(18,2)           DEFAULT 0.00,
        count_trans_recur_reg           INT                     DEFAULT 0,
        amount_trans_recur_reg          NUMERIC(18,2)           DEFAULT 0.00,
        count_trans_onetime_reg         INT                     DEFAULT 0,
        amount_trans_onetime_reg        NUMERIC(18,2)           DEFAULT 0.00,
        count_eft_recur_reg             INT                     DEFAULT 0,
        amount_eft_recur_reg            NUMERIC(18,2)           DEFAULT 0.00,
        count_eft_onetime_reg           INT                     DEFAULT 0,
        amount_eft_onetime_reg          NUMERIC(18,2)           DEFAULT 0.00,
        count_direct_debit_reg          INT                     DEFAULT 0,
        amount_direct_debit_reg         NUMERIC(18,2)           DEFAULT 0.00,
        count_interac_reg               INT                     DEFAULT 0,
        amount_interac_reg              NUMERIC(18,2)           DEFAULT 0.00,
        count_visa_recur_reg            INT                     DEFAULT 0,
        amount_visa_recur_reg           NUMERIC(18,2)           DEFAULT 0.00,
        count_visa_onetime_reg          INT                     DEFAULT 0,
        amount_visa_onetime_reg         NUMERIC(18,2)           DEFAULT 0.00,
        count_mc_recur_reg              INT                     DEFAULT 0,
        amount_mc_recur_reg             NUMERIC(18,2)           DEFAULT 0.00,
        count_mc_onetime_reg            INT                     DEFAULT 0,
        amount_mc_onetime_reg           NUMERIC(18,2)           DEFAULT 0.00,
        count_visadebit_recur_reg       INT                     DEFAULT 0,
        amount_visadebit_recur_reg      NUMERIC(18,2)           DEFAULT 0.00,
        count_visadebit_onetime_reg     INT                     DEFAULT 0,
        amount_visadebit_onetime_reg    NUMERIC(18,2)           DEFAULT 0.00,
        tenant_login_week               INT                     DEFAULT 0,
        tenant_login_month              INT                     DEFAULT 0,
        total_maint_requests            INT                     DEFAULT 0,
        maint_requests_month            INT                     DEFAULT 0,
        tenant_maint_requests           INT                     DEFAULT 0,
        tenant_maint_requests_month     INT                     DEFAULT 0,
                CONSTRAINT building_stats_pmc_propcode_week_uq UNIQUE (pmc,property_code,stats_week)
);

